### ISSUE TITLE
EasyBuild install task fails in ohpc-add-easybuild role

### ISSUE THREAD

**Issue by jprorama** [jprorama/CRI_XCBC#128]
The easybuild install task is failing due to some incompatibility of the 4.0.0 release with our current install environment.

**Comment by jprorama** [comment]
Since easy build is installed via the bootstrap script, it will ideally have a way to explicitly set the version.

This is accomplished through an [env EASYBUILD_BOOTSTRAP_FORCE_VERSION](https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/scripts/bootstrap_eb.py#L843)

Setting this in a test rule fixes the build-time error:
```yaml
- name: Boostrap EasyBuild
  shell: |
      source /opt/ohpc/admin/lmod/lmod/init/bash
      export EASYBUILD_BOOTSTRAP_FORCE_VERSION=3.9.4
      python bootstrap_eb.py "{{ easybuild_prefix }}"
  become_user: build
  args:
    executable: /bin/bash
    chdir: /tmp
```
