### ISSUE TITLE
ansible `aws_s3` module & `boto3` dependency failure in role `ood_shib_config`

### ISSUE THREAD

**Issue by eesaanatluri** [jprorama/CRI_XCBC#387]
Error:
```
    openstack.image: TASK [ood_shib_config : Install require package] *******************************
    openstack.image: fatal: [ood]: FAILED! => changed=false
    openstack.image:   msg: Unable to find any of pip2, pip to use.  pip needs to be installed.
    openstack.image:
    openstack.image: PLAY RECAP *********************************************************************
    openstack.image: ood                        : ok=29   changed=27   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```
Description:
- aws_s3 module in ansible is used to download shib config tar from s3. This module has a dependency on `boto3` pkg. `boto3` is a Python3 only package.
Solution: 
    - Need `pip3` and `Python3` to install boto3.

- boto3 pkg install still fails after fixing above issue as it can't find the pip3 executable. 
Solution: 
    - point the task to pip3 executable.

- As the ansible module to download the shib config tar is inherently dependent on Python3, we need to set the task to use a Python3 interpreter.
Solution:
    - Set the interpreter at task level to point to Python3. 
     NOTE: This wouldn't work if we set it globally in `/etc/ansible/ansible.cfg` because it would break yum installs in all the previous tasks and roles in the playbook because ansible uses Python2.X under the hood for yum module. So the yum install from the first solution would also break.
